### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by jonahweissman** [ipfs-shipyard/IGiS#36]
When I go to http://igis.io/, I see a blank page and the following error in the console:
```
Uncaught TypeError: Cannot read property 'generateKey' of undefined
    at Object.exports.generateKey (main.655b26fd.js:sourcemap:73915)
    at Object.generateKeyPair (main.655b26fd.js:sourcemap:162517)
    at Object.exports.generateKeyPair (main.655b26fd.js:sourcemap:158934)
    at waterfall (main.655b26fd.js:sourcemap:7521)
    at nextTask (main.655b26fd.js:sourcemap:2557)
    at exports.default (main.655b26fd.js:sourcemap:2567)
    at Function.exports.create (main.655b26fd.js:sourcemap:7520)
    at waterfall (main.655b26fd.js:sourcemap:194106)
    at nextTask (main.655b26fd.js:sourcemap:2557)
    at next (main.655b26fd.js:sourcemap:2564)
    at main.655b26fd.js:sourcemap:18411
    at db.get (main.655b26fd.js:sourcemap:23832)
    at dispatchError (main.655b26fd.js:sourcemap:58213)
    at main.655b26fd.js:sourcemap:142895
    at IDBRequest.req.onsuccess (main.655b26fd.js:sourcemap:24109)
Uncaught Error: Callback was already called.
    at main.655b26fd.js:sourcemap:18408
    at db.get (main.655b26fd.js:sourcemap:23835)
    at dispatchError (main.655b26fd.js:sourcemap:58213)
    at main.655b26fd.js:sourcemap:142895
    at IDBTransaction.tx.onabort (main.655b26fd.js:sourcemap:24085)
```

**Comment by magik6k** [comment]
So there are 2 issues:
* visiting from http is broken as js-ipfs requires secure context (https and/or localhost)
* https certs on https://igis.io/ are broken

**Comment by VictorBjelkholm** [comment]
Hm, why is the https-certs broken? Expired? We might also just have missed to configure igis.io to be part of the ssl setup we have.

**Comment by VictorBjelkholm** [comment]
Solved!

**Comment by jonahweissman** [comment]
the https cert is fixed!

however, the page still isn't loading, at least for me. I get this error in the console:

```
Uncaught 
err
cause:undefined
message:"QuotaExceededError"
name:"WriteError"
stack:"WriteError: QuotaExceededError
       at https://igis.io/static/js/main.7dc07f39.js:143298:34
       at IDBTransaction.tx.onabort (https://igis.io/static/js/main.7dc07f39.js:24157:5)"
type:"WriteError"
```

**Comment by magik6k** [comment]
What is your browser? Did you get a dialog about storing data locally?

**Comment by jonahweissman** [comment]
I'm using Google Chrome 66.0.3359.181 (Official Build) (64-bit) on a Chromebook. I've never seen any dialogs when visiting the page

**Comment by achingbrain** [comment]
I had the same `Uncaught TypeError: Cannot read property 'generateKey' of undefined` issue when visiting the `http` version of the site having never visited the `https` version.

After visiting the `https` version for the first time, subsequent visits to the `http` version forwards you on to the `https` version and all seems well.

**Comment by magik6k** [comment]
No https redirect is probably a gateway issue.

cc @scout can you have a look?
