### ISSUE TITLE
Currently broken

### ISSUE THREAD

**Issue by daviddias** [ipfs-shipyard/IGiS#53]
@magik6k was about to demo IGiS to some folks but discovered it hasn't been maintained. Is this something you can look into?

**Comment by magik6k** [comment]
I've tried to fix this by updating dependencies (pulling in the many js-ipfs improvements), but NPM is throwing some weird errors at me. It would be great if someone from deeper within js land could have a look.

**Comment by daviddias** [comment]
@magik6k can you share the error log?

**Comment by magik6k** [comment]
After updating with `npm-check-updates -u`, I'm getting this on `npm start`:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start-js' ]
2 info using npm@6.9.0
3 info using node@v11.15.0
4 verbose run-script [ 'prestart-js', 'start-js', 'poststart-js' ]
5 info lifecycle igis@0.1.0~prestart-js: igis@0.1.0
6 info lifecycle igis@0.1.0~start-js: igis@0.1.0
7 verbose lifecycle igis@0.1.0~start-js: unsafe-perm in lifecycle true
8 verbose lifecycle igis@0.1.0~start-js: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/magik6k/Developmet/igis/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/magik6k/Developmet/igis/node_modules/.bin:/home/magik6k/perl5/bin:/home/magik6k/.opt/bin:/home/magik6k/.opt/go/bin:/bin:/sbin:/usr/bin:/usr/sbin:/home/magik6k/Developmet/igis/node_modules/.bin:/home/magik6k/perl5/bin:/home/magik6k/.opt/bin:/home/magik6k/.opt/go/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/emulator:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/emscripten:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/vogl:/home/magik6k/.gem/ruby/2.3.0/bin:/usr/local/go/bin:/home/magik6k/bin:/home/magik6k/.npm-global/bin:/home/magik6k/.gem/ruby/2.3.0/bin:/usr/local/go/bin:/home/magik6k/bin:/home/magik6k/.npm-global/bin
9 verbose lifecycle igis@0.1.0~start-js: CWD: /home/magik6k/Developmet/igis
10 silly lifecycle igis@0.1.0~start-js: Args: [ '-c', 'node scripts/start.js' ]
11 silly lifecycle igis@0.1.0~start-js: Returned: code: 1  signal: null
12 info lifecycle igis@0.1.0~start-js: Failed to exec start-js script
13 verbose stack Error: igis@0.1.0 start-js: `node scripts/start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:193:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:193:13)
13 verbose stack     at maybeClose (internal/child_process.js:999:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
14 verbose pkgid igis@0.1.0
15 verbose cwd /home/magik6k/Developmet/igis
16 verbose Linux 5.0.13-arch1-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "start-js"
18 verbose node v11.15.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error igis@0.1.0 start-js: `node scripts/start.js`
22 error Exit status 1
23 error Failed at the igis@0.1.0 start-js script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by daviddias** [comment]
@magik6k can you change to an LTS version of Node.js and then `rm -rf node_modules && npm install` for good measure?

**Comment by magik6k** [comment]
With [10.15.3](https://www.archlinux.org/packages/community/x86_64/nodejs-lts-dubnium/) on `npm start` I'm getting:

```
> igis@0.1.0 start /home/magik6k/Developmet/igis
> npm-run-all -p watch-css start-js


> igis@0.1.0 watch-css /home/magik6k/Developmet/igis
> npm run build-css && node-sass-chokidar src/styles/scss/ -o src/styles/css/ --watch --recursive


> igis@0.1.0 start-js /home/magik6k/Developmet/igis
> node scripts/start.js


> igis@0.1.0 build-css /home/magik6k/Developmet/igis
> node-sass-chokidar src/styles/scss/ -o src/styles/css/

Rendering Complete, saving .css file...
Wrote CSS to /home/magik6k/Developmet/igis/src/styles/css/main.css
Wrote 1 CSS files to /home/magik6k/Developmet/igis/src/styles/css/
=> changed: /home/magik6k/Developmet/igis/src/styles/scss/main.scss
Failed to compile.

webpack is not a function

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! igis@0.1.0 start-js: `node scripts/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the igis@0.1.0 start-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Rendering Complete, saving .css file...

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/magik6k/.npm/_logs/2019-05-22T17_57_52_967Z-debug.log
Wrote CSS to /home/magik6k/Developmet/igis/src/styles/css/main.css
ERROR: "start-js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! igis@0.1.0 start: `npm-run-all -p watch-css start-js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the igis@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/magik6k/.npm/_logs/2019-05-22T17_57_53_064Z-debug.log

```

And in the log file:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/bin/npm', 'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle igis@0.1.0~prestart: igis@0.1.0
6 info lifecycle igis@0.1.0~start: igis@0.1.0
7 verbose lifecycle igis@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle igis@0.1.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/magik6k/Developmet/igis/node_modules/.bin:/home/magik6k/perl5/bin:/home/magik6k/.opt/bin:/home/magik6k/.opt/go/bin:/bin:/sbin:/usr/bin:/usr/sbin:/home/magik6k/Developmet/igis/node_modules/.bin:/home/magik6k/perl5/bin:/home/magik6k/.opt/bin:/home/magik6k/.opt/go/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/emulator:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/emscripten:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/vogl:/home/magik6k/.gem/ruby/2.3.0/bin:/usr/local/go/bin:/home/magik6k/bin:/home/magik6k/.npm-global/bin:/home/magik6k/.gem/ruby/2.3.0/bin:/usr/local/go/bin:/home/magik6k/bin:/home/magik6k/.npm-global/bin
9 verbose lifecycle igis@0.1.0~start: CWD: /home/magik6k/Developmet/igis
10 silly lifecycle igis@0.1.0~start: Args: [ '-c', 'npm-run-all -p watch-css start-js' ]
11 silly lifecycle igis@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle igis@0.1.0~start: Failed to exec start script
13 verbose stack Error: igis@0.1.0 start: `npm-run-all -p watch-css start-js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid igis@0.1.0
15 verbose cwd /home/magik6k/Developmet/igis
16 verbose Linux 5.0.13-arch1-1-ARCH
17 verbose argv "/usr/bin/node" "/bin/npm" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error igis@0.1.0 start: `npm-run-all -p watch-css start-js`
22 error Exit status 1
23 error Failed at the igis@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

(removed / reinstalled node_modules)

**Comment by dirkmc** [comment]
@daviddias I was able to successfully run `npm install && npm start` from master. What is the issue you're seeing?

**Comment by daviddias** [comment]
@dirkmc I looked at http://igis.io/ and I remember there were some errors, but now it seems it doesn't finish loading for me.

**Comment by dirkmc** [comment]
Ah I see, I'm not sure about igis.io, but if you just want to demo you can also run it locally.

@magik6k is the data for the demo repos pinned somewhere?

**Comment by daviddias** [comment]
@dirkmc I wanted to be able to point people to it :)

**Comment by dirkmc** [comment]
I see :) We should definitely get igis.io working.

If you want to send something to people right now, I created a couple of demo videos:
1. [Basic functionality](https://www.youtube.com/watch?v=FXsezRZXnWA)
2. [Pull Request functionality](https://github.com/ipfs-shipyard/IGiS/pull/47) (this is in a PR - can be configured to use OrbitDB or peer-base)

**Comment by magik6k** [comment]
Everything is pinned on `QmVGX47BzePPqEzpkTwfUJogPZxHcifpSXsGdgyHjtk5t7`, which is at:
```
/ip4/51.75.35.194/tcp/4001/ipfs/QmVGX47BzePPqEzpkTwfUJogPZxHcifpSXsGdgyHjtk5t7
/ip4/51.75.35.194/tcp/4002/ws/ipfs/QmVGX47BzePPqEzpkTwfUJogPZxHcifpSXsGdgyHjtk5t7
/ip4/51.75.35.194/tcp/80/ws/ipfs/QmVGX47BzePPqEzpkTwfUJogPZxHcifpSXsGdgyHjtk5t7
/dns4/ipfs.devtty.eu/wss/ipfs/QmVGX47BzePPqEzpkTwfUJogPZxHcifpSXsGdgyHjtk5t7
```
(I've updated the node to 0.4.21-rc3, it might have helped)

We should automagically connect to the last address, but it looks like that was dropped in https://github.com/ipfs-shipyard/IGiS/commit/e5ba17270279a4bb9d8f355ca8f09ec95b8f6b3c#diff-1fdf421c05c1140f6d71444ea2b27638L11 (I'm not sure if that's deployed, as it seems like whatever is on igis.io is still connecting to that node)

Also make sure that you are connecting to https://igis.io and not `http` (I'm not sure why the redirect stopped working, probably infra related)

**Comment by dirkmc** [comment]
@magik6k my bad, I'll add that line back in so it connects to the that host on page load.

It seems like there's an issue connecting to the host over wss:

<img width="912" alt="Screen Shot 2019-05-24 at 11 19 18 AM" src="https://user-images.githubusercontent.com/169124/58338535-dc7b6c80-7e15-11e9-8db3-98af7459f7d2.png">

**Comment by magik6k** [comment]
Looking at nginx logs, I'm getting a lot of 500 errors, you may need to retry a few times (I'm looking into what causes that (nginx conf vs go-ipfs))

**Comment by magik6k** [comment]
(nginx is currently proxying 6k+ connections which it might not be too happy about)

**Comment by dirkmc** [comment]
ha wow :)

PR to connect to demo server on startup: https://github.com/ipfs-shipyard/IGiS/pull/55

**Comment by magik6k** [comment]
Hmm, I'm getting A LOT of
```
May 24 15:50:05 potato ipfs[14603]: 2019/05/24 15:50:05 http: superfluous response.WriteHeader call from github.com/libp2p/go-ws-transport.(*listener).ServeHTTP (listener.go:29)
```

from `ipfs daemon`, cc @Stebalien

**Comment by Stebalien** [comment]
https://github.com/libp2p/go-ws-transport/pull/44.

Unfortunately, that's not the cause of the bug. However, it _does_ mean we're failing to upgrade the websocket.

**Comment by Stebalien** [comment]
@magik6k which version of IPFS is that machine running?

**Comment by magik6k** [comment]
> which version

0.4.21-rc3 linux-amd64 from dists

> can't connect
Apparently 50k FDs is not enough FDs. bumped it up a bit (I have relay hop enabled there)
